version: '3.8'
services:
  devco:
    build: 
      context: .
      dockerfile: Dockerfile 
    restart: unless-stopped

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: DevCo2023
      POSTGRES_USER: postgresadmin
      POSTGRES_DB: postgres

volumes:
  postgres-data: